spring:
  config:
    import: optional:configserver:http://localhost:8888 # Importamos la configuracion del servidor de configuracion
  application:
    name: discovery-service

#Lo siguiente se pasa al discovery-service.yml
#  eureka:
 #   instance:
  #    hostname: localhost
   #   client:
    #    registerWithEureka: false
     #   fetch-registry: false
      #  serviceUrl:
       #   defaultZone: http://${eureka.instance.hostname}/${$server.port}/eureka/

  #server:
    #port: 8761

