spring:
  profiles:
    active: native # Selecciona el perfil de configuracion
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations # Ubicacion de los archivos de configuracion en el proyecto. Classpath es la carpeta resources

server:
  port: 8888 #Puerto del servidor
